# Generated by Django 5.0.6 on 2026-03-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_personframekeypoints_personshape_shapefitsettings'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='detectedperson',
            name='unique_video_track',
        ),
        migrations.RemoveConstraint(
            model_name='personframekeypoints',
            name='unique_person_frame',
        ),
        migrations.AlterField(
            model_name='shapefitsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='personframekeypoints',
            unique_together={('person', 'frame_idx')},
        ),
    ]
