# Generated by Django 5.0.6 on 2026-04-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_personframepose_face_hands'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avatar',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='group',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='avataredit',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='fittingjob',
            name='avatar',
        ),
        migrations.AlterUniqueTogether(
            name='personframepose',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='personframepose',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personshape',
            name='group',
        ),
        migrations.DeleteModel(
            name='ShapeFitSettings',
        ),
        migrations.DeleteModel(
            name='AvatarEdit',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='FittingJob',
        ),
        migrations.DeleteModel(
            name='PersonFramePose',
        ),
        migrations.DeleteModel(
            name='PersonShape',
        ),
    ]
